version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    tty: true
    stdin_open: true
    command: ash -c "yarn && yarn serve"

volumes:
  node_modules:
    driver: local